### ISSUE TITLE
Hyprexpo doesn't build with the latest 0.56.0

### ISSUE THREAD

**Issue by Impossibleclone** [hyprwm/Hyprland#15536]
shell returned:  -> cd /run/user/1000/hyprpm/impossibleclone && PKG_CONFIG_PATH="/var/cache/hyprpm/impossibleclone/headersRoot/share/pkgconfig:$PKG_CONFIG_PATH" make all
g++ -shared -fPIC -g -std=c++2b -Wno-c++11-narrowing -Wno-narrowing --no-gnu-unique -DHYPREXPO_VERSION='"v0.55.4-dev+01fd77f"' -I/var/cache/hyprpm/impossibleclone/headersRoot/include -I/var/cache/hyprpm/impossibleclone/headersRoot/include/hyprland/protocols -I/var/cache/hyprpm/impossibleclone/headersRoot/include/hyprland -I/var/cache/hyprpm/impossibleclone/headersRoot/include/hyprland/src -I/usr/include/libdrm -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-6 -pthread -I/usr/include/lua5.4 main.cpp Dispatchers.cpp PluginConfig.cpp Overview.cpp OverviewInteraction.cpp OverviewRender.cpp ExpoGesture.cpp OverviewPassElement.cpp HyprexpoLogic.cpp -o hyprexpo.so -lpangocairo-1.0 -lpango-1.0 -lcairo -lharfbuzz -lgobject-2.0 -lglib-2.0 -lxkbcommon -llua5.4 -lm
main.cpp: In function ‘void hkAddDamageA(void*, const Hyprutils::Math::CBox&)’:
main.cpp:41:78: error: invalid use of incomplete type ‘class CMonitor’
   41 |     if (!g_pOverview || !g_pOverview->shouldRenderOverviewForMonitor(PMONITOR->m_self.lock()) || g_pOverview->blockDamageReporting) {
      |                                                                              ^~
In file included from main.cpp:11:
Overview.hpp:20:7: note: forward declaration of ‘class CMonitor’
   20 | class CMonitor;
      |       ^~~~~~~~
main.cpp: In function ‘void hkAddDamageB(void*, const pixman_region32_t*)’:
main.cpp:52:78: error: invalid use of incomplete type ‘class CMonitor’
   52 |     if (!g_pOverview || !g_pOverview->shouldRenderOverviewForMonitor(PMONITOR->m_self.lock()) || g_pOverview->blockDamageReporting) {
      |                                                                              ^~
Overview.hpp:20:7: note: forward declaration of ‘class CMonitor’
   20 | class CMonitor;
      |       ^~~~~~~~
At global scope:
cc1plus: note: unrecognized command-line option ‘-Wno-c++11-narrowing’ may have been intended to silence earlier diagnostics
Dispatchers.cpp:12:10: fatal error: hyprland/src/helpers/Monitor.hpp: No such file or directory
   12 | #include <hyprland/src/helpers/Monitor.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Overview.cpp:20:10: fatal error: hyprland/src/managers/animation/AnimationManager.hpp: No such file or directory
   20 | #include <hyprland/src/managers/animation/AnimationManager.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
OverviewInteraction.cpp:7:10: fatal error: hyprland/src/helpers/Monitor.hpp: No such file or directory
    7 | #include <hyprland/src/helpers/Monitor.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
OverviewRender.cpp:12:10: fatal error: hyprland/src/managers/animation/DesktopAnimationManager.hpp: No such file or directory
   12 | #include <hyprland/src/managers/animation/DesktopAnimationManager.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
ExpoGesture.cpp:6:10: fatal error: hyprland/src/helpers/Monitor.hpp: No such file or directory
    6 | #include <hyprland/src/helpers/Monitor.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:42: hyprexpo.so] Error 1

✖ Plugin hyprexpo failed to build.
  This likely means that the plugin is either outdated, not yet available for your version, or broken.
  If you are on -git, update first
  Try re-running with -v to see more verbose output.

✔ all plugins built
✔ installed repository
✔ you can now enable the plugin(s) with hyprpm enable
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5 / 5  Done!
