### ISSUE TITLE
0.39.1: compilation error: ISO C++ forbids forward references to 'enum' types

### ISSUE THREAD

**Issue by AngryPenguinPL** [hyprwm/Hyprland#5617]
### Hyprland Version

0.39.1

### Bug or Regression?

Regression

### Description

Trying compile v0.39.1 and see this build errors:

```
../src/managers/CursorManager.cpp:15:27: error: ISO C++ forbids forward references to 'enum' types
DEBUG util.py:463:     15 | static void hcLogger(enum eHyprcursorLogLevel level, char* message) {
DEBUG util.py:463:        |                           ^
DEBUG util.py:463:  ../src/managers/CursorManager.cpp:15:47: error: variable has incomplete type 'enum eHyprcursorLogLevel'
DEBUG util.py:463:     15 | static void hcLogger(enum eHyprcursorLogLevel level, char* message) {
DEBUG util.py:463:        |                                               ^
DEBUG util.py:463:  ../src/managers/CursorManager.cpp:15:27: note: forward declaration of 'eHyprcursorLogLevel'
DEBUG util.py:463:     15 | static void hcLogger(enum eHyprcursorLogLevel level, char* message) {
DEBUG util.py:463:        |                           ^
DEBUG util.py:463:  ../src/managers/CursorManager.cpp:16:18: error: use of undeclared identifier 'HC_LOG_TRACE'
DEBUG util.py:463:     16 |     if (level == HC_LOG_TRACE)
DEBUG util.py:463:        |                  ^
DEBUG util.py:463:  In file included from ../src/managers/CursorManager.cpp:1:
DEBUG util.py:463:  In file included from /builddir/build/BUILD/hyprland-0.39.1-x86_64/hyprland-source/build/../src/pch/pch.hpp:1:
DEBUG util.py:463:  In file included from /builddir/build/BUILD/hyprland-0.39.1-x86_64/hyprland-source/build/../src/Compositor.hpp:3:
DEBUG util.py:463:  In file included from /usr/bin/../lib64/gcc/x86_64-openmandriva-linux-gnu/13.2.1/../../../../include/c++/13.2.1/memory:78:
DEBUG util.py:463:  /usr/bin/../lib64/gcc/x86_64-openmandriva-linux-gnu/13.2.1/../../../../include/c++/13.2.1/bits/unique_ptr.h:1070:34: error: no matching constructor for initialization of 'Hyprcursor::CHyprcursorManager'
DEBUG util.py:463:   1070 |     { return unique_ptr<_Tp>(new _Tp(std::forward<_Args>(__args)...)); }
DEBUG util.py:463:        |                                  ^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~
DEBUG util.py:463:  ../src/managers/CursorManager.cpp:23:26: note: in instantiation of function template specialization 'std::make_unique<Hyprcursor::CHyprcursorManager, const char *, void (&)(eHyprcursorLogLevel, char *)>' requested here
DEBUG util.py:463:     23 |     m_pHyprcursor = std::make_unique<Hyprcursor::CHyprcursorManager>(m_szTheme.empty() ? nullptr : m_szTheme.c_str(), hcLogger);
DEBUG util.py:463:        |                          ^
DEBUG util.py:463:  /usr/include/hyprcursor/hyprcursor.hpp:45:9: note: candidate constructor not viable: requires single argument 'themeName', but 2 arguments were provided
DEBUG util.py:463:     45 |         CHyprcursorManager(const char* themeName);
DEBUG util.py:463:        |         ^                  ~~~~~~~~~~~~~~~~~~~~~
DEBUG util.py:463:  /usr/include/hyprcursor/hyprcursor.hpp:43:11: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
DEBUG util.py:463:     43 |     class CHyprcursorManager {
DEBUG util.py:463:        |           ^~~~~~~~~~~~~~~~~~
DEBUG util.py:463:  ../src/managers/CursorManager.cpp:234:21: error: no matching function for call to 'make_unique'
DEBUG util.py:463:    234 |     m_pHyprcursor = std::make_unique<Hyprcursor::CHyprcursorManager>(name.empty() ? "" : name.c_str(), hcLogger);
DEBUG util.py:463:        |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
DEBUG util.py:463:  /usr/bin/../lib64/gcc/x86_64-openmandriva-linux-gnu/13.2.1/../../../../include/c++/13.2.1/bits/unique_ptr.h:1069:5: note: candidate template ignored: substitution failure [with _Tp = Hyprcursor::CHyprcursorManager, _Args = <const char *, void (&)(enum eHyprcursorLogLevel, char *)>]
DEBUG util.py:463:   1069 |     make_unique(_Args&&... __args)
```

Full build log: https://file-store.openmandriva.org/api/v1/file_stores/93233961f019fa253e1c0a0e107e83539a971857.log?show=true

Worth to add that previous relese 0.39.0-rev1 compile without any problems.

### How to reproduce

1. download source-v0.39.1.tar.gz
2. compile with clang 18.1.2
3. see build error

**Comment by vaxerski** [comment]
looks like outdated libhyprcursor.

At any rate, CI is green, this is on your end.

**Comment by AngryPenguinPL** [comment]
I use latest stable hyprcursor v0.1.7.
Should I use git?

**Comment by AngryPenguinPL** [comment]
Hi @vaxerski I just tested latest git hyprcursor and then hyprland 0.39.1 compile fine.
So yes, it require unreleased version.
It would be good to cut new release of hyprcursor. This help distros maintenance.

**Comment by vaxerski** [comment]
I don't think there has been anything changed regarding that since 0.1.7 but sure...

**Comment by vaxerski** [comment]
https://github.com/hyprwm/hyprcursor/releases/tag/v0.1.8
