### ISSUE TITLE
Glitches after GPU fix update

### ISSUE THREAD

**Issue by niksingh710** [hyprwm/Hyprland#4744]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 301b48b74087cc59753ffa144b215540e6f82831 dirty (renderer: fix invalid damage accumulation with invalid buffer_age).
Date: Sun Feb 18 21:34:08 2024
Tag: v0.35.0-49-g301b48b7

flags: (if any)


System Information:
System name: Linux
Node name: mach
Release: 6.7.5-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Sat, 17 Feb 2024 14:02:21 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation CometLake-U GT2 [UHD Graphics] [8086:9b41] (rev 02) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:


```

</details>

### Bug or Regression?

Bug

### Description

Some time launching applications seeing artifacts of glitches.

### How to reproduce

After the discord announcement of gpu 
> considerable gpu performance hit from a commit introduced in v0.33.0 has been fixed in git. 
i updated hyprland-git.

Now launching apps like firefox sometime show glitches before rendering it is so fast that m failing to take screenshot.
will attach if got any.

**Comment by niksingh710** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/60490474/4e72174d-b008-4687-a0c4-fb2ac6f0ae8c)

**Comment by niksingh710** [comment]
The glitch is not like this but screenshot tool (grim) getting this

**Comment by tharrmeehan** [comment]
Can confirm this. For example while writing this comment, the text only refreshed after mouse movement. (tried enabling and disabling mouse_move_enables_dpms too)

**Comment by vaxerski** [comment]
can someone record it?

**Comment by Agent00Ming** [comment]
https://github.com/hyprwm/Hyprland/assets/107314235/6e02e133-d36e-4b37-8afe-4463e8437255

**Comment by Seme4eg** [comment]
https://github.com/hyprwm/Hyprland/assets/24554850/8cc6cec3-39c3-4fd7-9369-b40e62801225

**Comment by vaxerski** [comment]
can I get a log

**Comment by epicgamer256705** [comment]
I also have this bug here is my log:
```
[LOG] Instance Signature: 301b48b74087cc59753ffa144b215540e6f82831_1708288882
[LOG] Hyprland PID: 7505
[LOG] ===== SYSTEM INFO: =====
[LOG] System name: Linux
[LOG] Node name: matteo-laptop
[LOG] Release: 6.1.77
[LOG] Version: #1-NixOS SMP PREEMPT_DYNAMIC Mon Feb  5 20:13:03 UTC 2024


[LOG] GPU information:
0000:00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] [8086:9a49] (rev 01) (prog-if 00 [VGA controller])


[LOG] os-release:
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240207.f8e2ebd"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"

[LOG] ========================



[INFO] If you are crashing, or encounter any bugs, please consult https://wiki.hyprland.org/Crashes-and-Bugs/


[LOG]
Current splash: We're all living in America, America, America.


[LOG] Creating the HookSystem!
[LOG] Creating the KeybindManager!
[LOG] [hookSystem] New hook event registered: configReloaded
[LOG] Creating the AnimationManager!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 41.86µs. Estimated average calc time: 0.10µs.
[LOG] Creating the ConfigManager!
[LOG] NOTE: further logs to stdout / logfile are disabled by default. Use debug:disable_logs and debug:enable_stdout_logs to override this.
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 24.54µs. Estimated average calc time: 0.10µs.
[LOG] Using config: /home/matteo/.config/hypr/hyprland.conf
```

**Comment by Seme4eg** [comment]
http://0x0.st/Hnvx.txt

**Comment by epicgamer256705** [comment]
here's my log: https://0x0.st/Hnvn.log

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/14324837/patch.txt)
try

**Comment by rurigk** [comment]
@vaxerski your patch does not contain your changes in wlroots
```
diff --git a/subprojects/wlroots b/subprojects/wlroots
--- a/subprojects/wlroots
+++ b/subprojects/wlroots
@@ -1 +1 @@
-Subproject commit 00b869c1a96f300a8f25da95d624524895e0ddf2
+Subproject commit 00b869c1a96f300a8f25da95d624524895e0ddf2-dirty
```

How i apply that patch? im assuming you modified something in wlroots?

**Comment by vaxerski** [comment]
no, thats just git being git. `patch -p1 < /path/to/patch.txt` and it should just work

**Comment by Seme4eg** [comment]
didn't work for me, needed to remove that `-dirty` part

**Comment by rurigk** [comment]
I tested the patch and it didnt work

Before 301b48b74087cc59753ffa144b215540e6f82831

https://github.com/hyprwm/Hyprland/assets/6665402/5625de20-c4dd-4c15-8d40-81079abed24e

After 301b48b74087cc59753ffa144b215540e6f82831 with and without your patch

https://github.com/hyprwm/Hyprland/assets/6665402/7b4de2d9-07f2-4a49-bc86-1b19dc60db58

Im on AMD card 6700xt, for me its just the screen capture not the whole screen

**Comment by vaxerski** [comment]
wait it's _only_ screencopy?

**Comment by rurigk** [comment]
Check the video of @Seme4eg https://github.com/hyprwm/Hyprland/issues/4744#issuecomment-1951432467
@Seme4eg its your whole desktop or its just screencopy?

**Comment by Agent00Ming** [comment]
Foot is affected while Kitty is not. Firefox with hw-accel enabled works flawlessly but it has lots of artifacting with it turned off. Kate, Dolphin and Libreoffice suite are affected. I tried out the patch with the same results.

**Comment by vaxerski** [comment]
pretty sure it's unrelated to this patch and this patch has just shown it. Can someone try and take the commit as a patch, and bisect but with that patch applied? It should work for every rev after ~0.33.0.

soo bisect but before testing any commit apply the patch that caused this behavior.

Pretty sure if you apply this to 0.33.0 it wont cause this. I'll explain more tomorrow if necessary its 4am and I have class tmr

**Comment by Seme4eg** [comment]
@rurigk , those artifacts appear only on wayland windows, xwayland ones don't have them, and all other animations like switching workspaces don't products artifacts.

**Comment by Seme4eg** [comment]
What 'fixed' it for me is removing scaling from my monitor. I have a hidpi 4k laptop screen i usually scale by 1.8. Removing it fixed those artifacts, but i have everything super tiny now

**Comment by rurigk** [comment]
I don't use any scaling, can you test desktop capture with no scaling?

**Comment by fufexan** [comment]
I'm only noticing the glitches in GTK apps so far, with scaling 1.6. Unscaled works fine.

**Comment by Seme4eg** [comment]
> I don't use any scaling, can you test desktop capture with no scaling?

https://github.com/hyprwm/Hyprland/assets/24554850/b5627fd3-dad2-4274-8742-a84e4667c046

Without scaling yes, still borked

**Comment by sentakuhm** [comment]
i upgraded to -git just now and i faced same issue, unscale fixed this issue.

**Comment by vaxerski** [comment]
thanks for fucking doing what I asked for. Just like I said, c4365f20ed8ff0dd480b7ed7cf1bfff1a0b6911a was the real faulty commit.

Anyways fixed for me with above.

**Comment by vaxerski** [comment]
minor oopsies with fs-v1 surfaces fixed in the subsequent 176356630853a6558b8125726bbdaf6411593488

All issues here should be solved.

**Comment by KrolixW** [comment]
Still glitches for me

**Comment by Seme4eg** [comment]
noticable visual glitches fixed for me, but screen recording is still borked.

**Comment by KrolixW** [comment]
> No it doesn't.

yes it does. Most often it happens when notification disappears, but i still cannot reproduce it consistently.

https://github.com/hyprwm/Hyprland/assets/79580247/a8ba08e4-7824-4324-8fb9-669e950a2d06

had to record via camera because obs recording has its own glitches

https://github.com/hyprwm/Hyprland/assets/79580247/5e84e44b-955b-433e-a930-20681d1f2404

**Comment by Seme4eg** [comment]
try to cleanbuild hyprland and reboot the machine and if it still persists, then try to bisect commits

**Comment by niksingh710** [comment]
Updated and not faced it yet.
Will try for a while and if no issue comes up then I guess this issue should be close.

**Comment by vaxerski** [comment]
@KrolixW that does _not_ look like this issue. That looks like your gpu driver giving up

**Comment by niksingh710** [comment]
> @KrolixW that does _not_ look like this issue. That looks like your gpu driver giving up

The issue is there I am on latest hyprland

It happens so rare and so quickly that can't record.

Mostly faced on foot terminal

**Comment by Fxzzi** [comment]
Wish I could vax but I'm a little busy right now. If nobody is competent enough to do it by the time I'm free I'll do it myself.

**Comment by Fxzzi** [comment]
P.s. the patch you're talking about is this? https://github.com/hyprwm/Hyprland/issues/4744#issuecomment-1951481092

**Comment by vaxerski** [comment]
no, this: https://github.com/hyprwm/Hyprland/commit/301b48b74087cc59753ffa144b215540e6f82831

**Comment by Fxzzi** [comment]
Thanks bb, will test now :)

**Comment by Fxzzi** [comment]
Seems I am unable to apply the patch and build correctly on 0.33.0 and 0.34.0

```FAILED: CMakeFiles/Hyprland.dir/src/render/Renderer.cpp.o 
/usr/bin/c++ -DHAS_EXECINFO -DHyprland_EXPORTS -DUSES_SYSTEMD -DWLR_USE_UNSTABLE -I/home/faaris/Hyprland/. -I/home/faaris/Hyprland/src -I/home/faaris/Hyprland/subprojects/wlroots/include -I/home/faaris/Hyprland/subprojects/wlroots/build/include -I/home/faaris/Hyprland/subprojects/udis86 -I/home/faaris/Hyprland/protocols -I/home/faaris/Hyprland/subprojects/udis86/libudis86 -isystem /usr/include/libdrm -isystem /usr/include/pango-1.0 -isystem /usr/include/cairo -isystem /usr/include/freetype2 -isystem /usr/include/harfbuzz -isystem /usr/include/glib-2.0 -isystem /usr/lib/glib-2.0/include -isystem /usr/include/pixman-1 -isystem /usr/include/libmount -isystem /usr/include/blkid -isystem /usr/include/fribidi -isystem /usr/include/libpng16 -isystem /usr/include/sysprof-6 -O3 -DNDEBUG -std=gnu++23 -O3 -Wall -Wextra -Wno-unused-parameter -Wno-unused-value -Wno-missing-field-initializers -Wno-narrowing -Wno-pointer-arith -pthread -Winvalid-pch -include /home/faaris/Hyprland/build/CMakeFiles/Hyprland.dir/cmake_pch.hxx -MD -MT CMakeFiles/Hyprland.dir/src/render/Renderer.cpp.o -MF CMakeFiles/Hyprland.dir/src/render/Renderer.cpp.o.d -o CMakeFiles/Hyprland.dir/src/render/Renderer.cpp.o -c /home/faaris/Hyprland/src/render/Renderer.cpp
/home/faaris/Hyprland/src/render/Renderer.cpp: In member function ‘void CHyprRenderer::renderMonitor(CMonitor*)’:
/home/faaris/Hyprland/src/render/Renderer.cpp:1084:58: error: ‘m_iLastBufferAge’ was not declared in this scope
 1084 |     wlr_damage_ring_get_buffer_damage(&pMonitor->damage, m_iLastBufferAge, damage.pixman());
      |                                                          ^~~~~~~~~~~~~~~~
[108/114] Building CXX object CMakeFiles/Hyprland.dir/src/render/OpenGL.cpp.o
ninja: build stopped: subcommand failed.
make[1]: *** [Makefile:15: release] Error 1
make[1]: Leaving directory '/home/faaris/Hyprland'
make: *** [Makefile:31: all] Error 2```

**Comment by tharrmeehan** [comment]
The issue got fixed for me, thank you very much.

**Comment by vaxerski** [comment]
aarrgghh git

**Comment by vaxerski** [comment]
[patchtttt.txt](https://github.com/hyprwm/Hyprland/files/14336141/patchtttt.txt)
try this

**Comment by alba4k** [comment]
![immagine](https://github.com/hyprwm/Hyprland/assets/84153269/68ed285d-c750-4618-b073-67879f7f5d5c)


funny screenshot I was able to capture while opening telegram

**Comment by vaxerski** [comment]
screencopy was not touched. it's only for normal usage

**Comment by Fxzzi** [comment]
Vax, the patch u sent is empty btw

**Comment by vaxerski** [comment]
fucking git
[patchtttt.txt](https://github.com/hyprwm/Hyprland/files/14336258/patchtttt.txt)

**Comment by Fxzzi** [comment]
patch still failing on v0.34.0

```
FAILED: CMakeFiles/Hyprland.dir/src/config/ConfigManager.cpp.o 
/usr/bin/c++ -DHAS_EXECINFO -DHyprland_EXPORTS -DUSES_SYSTEMD -DWLR_USE_UNSTABLE -I/home/faaris/Hyprland/. -I/home/faaris/Hyprland/src -I/home/faaris/Hyprland/subprojects/wlroots/include -I/home/faaris/Hyprland/subprojects/wlroots/build/include -I/home/faaris/Hyprland/subprojects/udis86 -I/home/faaris/Hyprland/protocols -I/home/faaris/Hyprland/subprojects/udis86/libudis86 -isystem /usr/include/libdrm -isystem /usr/include/pango-1.0 -isystem /usr/include/cairo -isystem /usr/include/freetype2 -isystem /usr/include/harfbuzz -isystem /usr/include/glib-2.0 -isystem /usr/lib/glib-2.0/include -isystem /usr/include/pixman-1 -isystem /usr/include/libmount -isystem /usr/include/blkid -isystem /usr/include/fribidi -isystem /usr/include/libpng16 -isystem /usr/include/sysprof-6 -O3 -DNDEBUG -std=gnu++23 -O3 -Wall -Wextra -Wno-unused-parameter -Wno-unused-value -Wno-missing-field-initializers -Wno-narrowing -Wno-pointer-arith -pthread -Winvalid-pch -include /home/faaris/Hyprland/build/CMakeFiles/Hyprland.dir/cmake_pch.hxx -MD -MT CMakeFiles/Hyprland.dir/src/config/ConfigManager.cpp.o -MF CMakeFiles/Hyprland.dir/src/config/ConfigManager.cpp.o.d -o CMakeFiles/Hyprland.dir/src/config/ConfigManager.cpp.o -c /home/faaris/Hyprland/src/config/ConfigManager.cpp
/home/faaris/Hyprland/src/config/ConfigManager.cpp: In lambda function:
/home/faaris/Hyprland/src/config/ConfigManager.cpp:2307:17: error: ‘wlr_output_enable_adaptive_sync’ was not declared in this scope
 2307 |                 wlr_output_enable_adaptive_sync(m->output, 0);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/faaris/Hyprland/src/config/ConfigManager.cpp:2309:22: error: ‘wlr_output_commit’ was not declared in this scope; did you mean ‘wlr_output_init’?
 2309 |                 if (!wlr_output_commit(m->output))
      |                      ^~~~~~~~~~~~~~~~~
      |                      wlr_output_init
/home/faaris/Hyprland/src/config/ConfigManager.cpp:2316:17: error: ‘wlr_output_enable_adaptive_sync’ was not declared in this scope
 2316 |                 wlr_output_enable_adaptive_sync(m->output, 1);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/faaris/Hyprland/src/config/ConfigManager.cpp:2318:22: error: ‘wlr_output_test’ was not declared in this scope; did you mean ‘wlr_output_init’?
 2318 |                 if (!wlr_output_test(m->output)) {
      |                      ^~~~~~~~~~~~~~~
      |                      wlr_output_init
/home/faaris/Hyprland/src/config/ConfigManager.cpp:2323:22: error: ‘wlr_output_commit’ was not declared in this scope; did you mean ‘wlr_output_init’?
 2323 |                 if (!wlr_output_commit(m->output))
      |                      ^~~~~~~~~~~~~~~~~
      |                      wlr_output_init
/home/faaris/Hyprland/src/config/ConfigManager.cpp:2340:17: error: ‘wlr_output_enable_adaptive_sync’ was not declared in this scope
 2340 |                 wlr_output_enable_adaptive_sync(m->output, 1);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/faaris/Hyprland/src/config/ConfigManager.cpp:2342:22: error: ‘wlr_output_test’ was not declared in this scope; did you mean ‘wlr_output_init’?
 2342 |                 if (!wlr_output_test(m->output)) {
      |                      ^~~~~~~~~~~~~~~
      |                      wlr_output_init
/home/faaris/Hyprland/src/config/ConfigManager.cpp:2347:22: error: ‘wlr_output_commit’ was not declared in this scope; did you mean ‘wlr_output_init’?
 2347 |                 if (!wlr_output_commit(m->output))
      |                      ^~~~~~~~~~~~~~~~~
      |                      wlr_output_init
/home/faaris/Hyprland/src/config/ConfigManager.cpp:2351:17: error: ‘wlr_output_enable_adaptive_sync’ was not declared in this scope
 2351 |                 wlr_output_enable_adaptive_sync(m->output, 0);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/faaris/Hyprland/src/config/ConfigManager.cpp:2353:22: error: ‘wlr_output_commit’ was not declared in this scope; did you mean ‘wlr_output_init’?
 2353 |                 if (!wlr_output_commit(m->output))
      |                      ^~~~~~~~~~~~~~~~~
      |                      wlr_output_init
[52/114] Building CXX object CMakeFiles/Hyprland.dir/src/debug/HyprCtl.cpp.o
ninja: build stopped: subcommand failed.
make[1]: *** [Makefile:15: release] Error 1
make[1]: Leaving directory '/home/faaris/Hyprland'
make: *** [Makefile:31: all] Error 2
```

**Comment by vaxerski** [comment]
what you mean didnt fix it? Or are you incapable of reading the patch is only meant for ON-SCREEN flicker and NOT screencopy??

**Comment by vaxerski** [comment]
d62e7a5125c551fe8a94e076e64d42b702d923b1 and e793f10b8bd1685a2e2bbd7cc90063f12bf380c4 fix both issues. Fix for screencopy fucking sucks but I give up writing a better one after 2 or so hours.

**Comment by Fxzzi** [comment]
Thanks for fixing the issues vax, take your time on the better fix, at least it's working fine now :)

**Comment by vaxerski** [comment]
chatted with wayland bois and I dont think the better fix is worth it due to.... wheyland

anyways closing fuck you all and I'll see you next time

**Comment by rurigk** [comment]
Both of them works for me

**Comment by niksingh710** [comment]
I am currently on 
```
Hyprland, built from branch main at commit 86be75dd97b5633b8c0aa6bdcb3346fa871a8480 dirty (events: bring back accidentally nuked preConfigReload).
Date: Tue Feb 20 08:54:15 2024
Tag: v0.35.0-59-g86be75dd

flags: (if any)

```

updated from `AUR` i face glitches sometime in foot terminal
is there someother way to build to get fixed or the issue is there ?

**Comment by niksingh710** [comment]
here after rebuild from aur
![image](https://github.com/hyprwm/Hyprland/assets/60490474/38759133-fb7c-4444-91bc-e03f945591fa)
facing this on foot till only for now.

**Comment by Fxzzi** [comment]
hello again vax. Seems your fixes may have solved in some cases but I seem to be experiencing the issue(s) still on my Thinkpad L14 (AMD CPU and iGPU)

![image](https://github.com/hyprwm/Hyprland/assets/18248986/50f1cd77-8ac8-488b-8d82-4daaaefbabd4)

Anything you need me to test? Once again sorry for the trouble

**Comment by vaxerski** [comment]
there are two issues here and I want you to not mix those up.

One is visible on-screen, one is only visible on recordings. Which are you talking about

**Comment by Fxzzi** [comment]
> there are two issues here and I want you to not mix those up.
> 
> One is visible on-screen, one is only visible on recordings. Which are you talking about

Yep, I understand. No issues afaik on screen. Issues with screencopy, aka OBS and Grim.

**Comment by vaxerski** [comment]
@niksingh710 your issue looks more like your gpu drivers crying than anything else. Nvidia?

@Fxzzi can you fiddle with your config on your laptop and see if any options solve the problem?

**Comment by Fxzzi** [comment]
> @Fxzzi can you fiddle with your config on your laptop and see if any options solve the problem?

For sure, I'll have a look for you when I can. I assume it'll just be something in Hyprland config?

For ref, here are all of my configs
https://gitlab.com/fazzi/dotfiles

**Comment by vaxerski** [comment]
yeah, try stuff like making your monitors at 0x0, changing res, maybe fiddle with rendering-related options

**Comment by niksingh710** [comment]
yesterday i tried the latest commit in one of my friends laptop he is having nvidia 1650 for him everything was working fine.
tears if nvidia_tear variable is false but the fps is 60
and if nvidia_tear is true then no tear but fps is 30.
(on kde wayland too he get's 30 fps on monitor screen)

**Comment by Fxzzi** [comment]
> yeah, try stuff like making your monitors at 0x0, changing res, maybe fiddle with rendering-related options

after fiddling a bit, it seems having waybar running and visible seems to break the screenshots. Here is my testing:

Minimal config:
<details>

```hyprlang
monitor = eDP-1,1920x1080@60,0x0,1 # Set display to max res, auto offset

$MOD = SUPER

bind = , Print, exec, screenshot.sh --monitor
bind = , XF86Launch2, exec, screenshot.sh --selection
bind = SHIFT, Print, exec, screenshot.sh --active

binde=, XF86AudioRaiseVolume, exec, audio.sh vol up 5
binde=, XF86AudioLowerVolume, exec, audio.sh vol down 5
binde=, XF86AudioMute, exec, audio.sh vol toggle
binde=, XF86AudioMicMute, exec, audio.sh mic toggle

binde=, XF86MonBrightnessUp, exec, brightness.sh up 5
binde=, XF86MonBrightnessDown, exec, brightness.sh down 5

bind = $MOD, T, exec, foot
bind = $MOD SHIFT, E, exec, pkill wleave || wleave --protocol layer-shell -b 5 -T 360 -B 360
bind = $MOD SHIFT, R, exec, hyprctl reload

bind = $MOD, Q, killactive
bind = $MOD, Space, fullscreen
bind = $MOD, Tab, togglefloating
bind = $MOD, P, pseudo # dwindle
bind = $MOD, S, togglesplit # dwindle

bind = $MOD, left, movefocus, l
bind = $MOD, right, movefocus, r
bind = $MOD, up, movefocus, u
bind = $MOD, down, movefocus, d

bind = $MOD SHIFT, left, movewindow, l
bind = $MOD SHIFT, right, movewindow, r
bind = $MOD SHIFT, up, movewindow, u
bind = $MOD SHIFT, down, movewindow, d

binde = $MOD CTRL, left, resizeactive, -10 0
binde = $MOD CTRL, right, resizeactive, 10 0
binde = $MOD CTRL, up, resizeactive, 0 -10
binde = $MOD CTRL, down, resizeactive, 0 10

bind = $MOD, 1, workspace, 1
bind = $MOD, 2, workspace, 2
bind = $MOD, 3, workspace, 3
bind = $MOD, 4, workspace, 4
bind = $MOD, 5, workspace, 5
bind = $MOD, 6, workspace, 6
bind = $MOD, 7, workspace, 7
bind = $MOD, 8, workspace, 8
bind = $MOD, 9, workspace, 9
bind = $MOD, 0, workspace, 10
bind = $MOD ALT, up, workspace, e+1
bind = $MOD ALT, down, workspace, e-1

bind = $MOD SHIFT, 1, movetoworkspace, 1
bind = $MOD SHIFT, 2, movetoworkspace, 2
bind = $MOD SHIFT, 3, movetoworkspace, 3
bind = $MOD SHIFT, 4, movetoworkspace, 4
bind = $MOD SHIFT, 5, movetoworkspace, 5
bind = $MOD SHIFT, 6, movetoworkspace, 6
bind = $MOD SHIFT, 7, movetoworkspace, 7
bind = $MOD SHIFT, 8, movetoworkspace, 8
bind = $MOD SHIFT, 9, movetoworkspace, 9
bind = $MOD SHIFT, 0, movetoworkspace, 10

bindm = $MOD, mouse:272, movewindow
bindm = $MOD, mouse:273, resizewindow
bind = $MOD, mouse_down, workspace, e+1
bind = $MOD, mouse_up, workspace, e-1
```

</details>
no issues with screenshots or video recording on this minimal config

Now for my config:
https://gitlab.com/fazzi/dotfiles/-/raw/hyprland-laptop/.config/hypr/hyprland.conf

Issue with screenshots:
![Screenshot from 24 02 20 14:07:54](https://github.com/hyprwm/Hyprland/assets/18248986/ee2952b2-ff7f-41e5-b55b-a29da51bfb75)

However, strangely, screen recording seems fine: 
![image](https://github.com/hyprwm/Hyprland/assets/18248986/f6d18fd4-3ffd-4450-be46-e36baaebf494)


Killing waybar and screenshots seem fixed from what I can tell:
![Screenshot from 24 02 20 14:07:21](https://github.com/hyprwm/Hyprland/assets/18248986/3b80e2b3-ccf1-45b3-a46b-21ccd94ec9b1)

I tested whether or not it was some issue with the waybar reserved area, however doesn't seem like it, as adding `monitor = eDP-1,addreserved,40,0,0,0` with waybar killed and screenshots are still good
![Screenshot from 24 02 20 14:09:07](https://github.com/hyprwm/Hyprland/assets/18248986/c3f45759-794e-4038-9a1c-dab5c6ed311d)

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/14346125/patch.txt)
le try

**Comment by vaxerski** [comment]
committed

**Comment by niksingh710** [comment]
> committed

screen copy wasn't an issue for me updated to latest commit
sometimes still i see artifacts on foot terminal 
After updating to latest git commit my laptop screen had abit of artifact but as cursor went their it cleaned up.

```log
[LOG] Instance Signature: 02c9a2d769dc3ae5efb942ad16578eee45a6f6dd_1708443832
[LOG] Hyprland PID: 977
[LOG] ===== SYSTEM INFO: =====
[LOG] System name: Linux
[LOG] Node name: mach
[LOG] Release: 6.7.5-zen1-1-zen
[LOG] Version: #1 ZEN SMP PREEMPT_DYNAMIC Sat, 17 Feb 2024 14:02:21 +0000


[LOG] GPU information:
00:02.0 VGA compatible controller [0300]: Intel Corporation CometLake-U GT2 [UHD Graphics] [8086:9b41] (rev 02) (prog-if 00 [VGA controller])


[LOG] os-release:
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

[LOG] ========================



[INFO] If you are crashing, or encounter any bugs, please consult https://wiki.hyprland.org/Crashes-and-Bugs/


[LOG]
Current splash: Never gonna let you down (I am trying!)


[LOG] Creating the HookSystem!
[LOG] Creating the KeybindManager!
[LOG] [hookSystem] New hook event registered: configReloaded
[LOG] Creating the AnimationManager!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 53.64µs. Estimated average calc time: 0.08µs.
[LOG] Creating the ConfigManager!
[LOG] NOTE: further logs to stdout / logfile are disabled by default. Use debug:disable_logs and debug:enable_stdout_logs to override this.
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 35.12µs. Estimated average calc time: 0.08µs.
[LOG] Using config: /home/niksingh710/.config/hypr/hyprland.conf

```

**Comment by vaxerski** [comment]
I see reading the third-to-last line of the log is difficult.

**Comment by niksingh710** [comment]
> I see reading the third-to-last line of the log is difficult.

Sarcasm ?....
Only this much was in logs ....

**Comment by alba4k** [comment]
@niksingh710 enable those options in your config, then post the log you get here

**Comment by niksingh710** [comment]
> @niksingh710 enable those options in your config, then post the log you get here

[Logs](https://gist.github.com/niksingh710/3269ecf5bbf0b7ad1535f400b0540fe6)

aaaah i literaly thought till date that `logs` are enabled by default 💢

**Comment by vaxerski** [comment]
![image](https://github.com/hyprwm/Hyprland/assets/43317083/d1ec038a-4b4f-478e-9be9-1ab8dae55850)

this is the source most likely, if you don't have tearing enabled explicitly then this signifies a driver issue.

**Comment by niksingh710** [comment]
@vaxerski in my observation 
if monitor is connected and then hyprland is launched the it's ok just glitches are there.
but if i disconnect monitor and then reconnect it to running hyprland instance everything freezes. and then reboot is the only option.

**Comment by alba4k** [comment]
I experienced this too

when disconnecting my laptop from the external monitors, I have to use REISUB

**Comment by niksingh710** [comment]
Could be totally unrelated.
But earlier when I used to reboot my system was kept on `ondemand` but now when I reboot it is on `schedutil`

**Comment by alba4k** [comment]
@vaxerski I'm fairly sure this should be reopened.

OBS Screen Recordings are fine now, sure, but I still do fairly often see weird graphical glitches appear on screen, usually after opening an app using rofi, before its window appears, or randomly on a monitor after flameshot closes, stuff like that. Looks like the exact same thing this issue was opened for

It is hard to record, as they are usually present for a very short time. But those glitches usually consist in some formation of randomly placed randomly colored pixels in a selected area (usually rectangles, about ~40% of pixels appear glitched)

I highly doubt that all of our gpu drivers decided do die all of a sudden, especially since the glitches seem to appear in specific situations.

**Comment by alba4k** [comment]
Managed to replicate it pretty consistently.

https://quickshare.samsungcloud.com/bRdRajgOMG1E

This is what this issue looks like, most of the time (similar glitches sometimes appear in smaller parts of the screen). It shows part of the window that was previously open, even though it might not even exist anymore. Also, as can be seen from this video, the opening time of firefox is a lot longer when the glitch appears (it should always be nearly instantaneous).

**Comment by vaxerski** [comment]
is this nvidia

**Comment by alba4k** [comment]
Nope, intel

**Comment by vaxerski** [comment]
open a different issue then, as this one is fixed.

**Comment by alba4k** [comment]
I guess the original issue was never fixed then, as @niksingh710 isn't using nvidia either.

But sure, I can open a different one

**Comment by vaxerski** [comment]
***this issue has been fixed.***

**Comment by Fxzzi** [comment]
> I guess the original issue was never fixed then

I tried with both AMD and Nvidia, vaxrys' fixes fixed it on both

**Comment by alba4k** [comment]
https://github.com/hyprwm/Hyprland/issues/4804
