### ISSUE TITLE
Fails to build on 32-bit architectures (e.g., armv7, i386, powerpc)

### ISSUE THREAD

**Issue by jbeich** [hyprwm/Hyprland#4895]
### Hyprland Version

v0.36.0 but 1698d336f251 snapshot is also affected.

### Bug or Regression?

Regression

### Description

Regressed by 13f6f0b923ff. See also https://github.com/hyprwm/hyprlang/issues/8

```c++
../src/config/ConfigManager.cpp:305:60: error: call to constructor of 'const CConfigValue &' is ambiguous
    m_pConfig->addConfigValue("general:apply_sens_to_raw", {0L});
                                                           ^~~~
../src/config/ConfigManager.cpp:306:54: error: call to constructor of 'const CConfigValue &' is ambiguous
    m_pConfig->addConfigValue("general:border_size", {1L});
                                                     ^~~~
../src/config/ConfigManager.cpp:307:64: error: call to constructor of 'const CConfigValue &' is ambiguous
    m_pConfig->addConfigValue("general:no_border_on_floating", {0L});
                                                               ^~~~
../src/config/ConfigManager.cpp:308:64: error: call to constructor of 'const CConfigValue &' is ambiguous
    m_pConfig->addConfigValue("general:border_part_of_window", {1L});
                                                               ^~~~
../src/config/ConfigManager.cpp:311:58: error: call to constructor of 'const CConfigValue &' is ambiguous
    m_pConfig->addConfigValue("general:gaps_workspaces", {0L});
                                                         ^~~~
../src/config/ConfigManager.cpp:312:66: error: call to constructor of 'const CConfigValue &' is ambiguous
    m_pConfig->addConfigValue("general:cursor_inactive_timeout", {0L});
                                                                 ^~~~
../src/config/ConfigManager.cpp:313:58: error: call to constructor of 'const CConfigValue &' is ambiguous
    m_pConfig->addConfigValue("general:no_cursor_warps", {0L});
                                                         ^~~~
../src/config/ConfigManager.cpp:314:60: error: call to constructor of 'const CConfigValue &' is ambiguous
    m_pConfig->addConfigValue("general:no_focus_fallback", {0L});
                                                           ^~~~
../src/config/ConfigManager.cpp:315:59: error: call to constructor of 'const CConfigValue &' is ambiguous
    m_pConfig->addConfigValue("general:resize_on_border", {0L});
                                                          ^~~~
../src/config/ConfigManager.cpp:316:66: error: call to constructor of 'const CConfigValue &' is ambiguous
    m_pConfig->addConfigValue("general:extend_border_grab_area", {15L});
                                                                 ^~~~~
../src/config/ConfigManager.cpp:317:63: error: call to constructor of 'const CConfigValue &' is ambiguous
    m_pConfig->addConfigValue("general:hover_icon_on_border", {1L});
                                                              ^~~~
../src/config/ConfigManager.cpp:319:56: error: call to constructor of 'const CConfigValue &' is ambiguous
    m_pConfig->addConfigValue("general:allow_tearing", {0L});
                                                       ^~~~
../src/config/ConfigManager.cpp:321:61: error: call to constructor of 'const CConfigValue &' is ambiguous
    m_pConfig->addConfigValue("misc:disable_hyprland_logo", {0L});
                                                            ^~~~
../src/config/ConfigManager.cpp:322:64: error: call to constructor of 'const CConfigValue &' is ambiguous
    m_pConfig->addConfigValue("misc:disable_splash_rendering", {0L});
                                                               ^~~~
../src/config/ConfigManager.cpp:323:50: error: call to constructor of 'const CConfigValue &' is ambiguous
    m_pConfig->addConfigValue("misc:col.splash", {0x55ffffffL});
                                                 ^~~~~~~~~~~~~
../src/config/ConfigManager.cpp:325:63: error: call to constructor of 'const CConfigValue &' is ambiguous
    m_pConfig->addConfigValue("misc:force_default_wallpaper", {-1L});
                                                              ^~~~~
../src/config/ConfigManager.cpp:326:43: error: call to constructor of 'const CConfigValue &' is ambiguous
    m_pConfig->addConfigValue("misc:vfr", {1L});
                                          ^~~~
../src/config/ConfigManager.cpp:327:43: error: call to constructor of 'const CConfigValue &' is ambiguous
    m_pConfig->addConfigValue("misc:vrr", {0L});
                                          ^~~~
../src/config/ConfigManager.cpp:328:63: error: call to constructor of 'const CConfigValue &' is ambiguous
    m_pConfig->addConfigValue("misc:mouse_move_enables_dpms", {0L});
                                                              ^~~~
/usr/include/hyprlang.hpp:192:9: note: candidate constructor
        CConfigValue(const INT value);
        ^
/usr/include/hyprlang.hpp:193:9: note: candidate constructor
        CConfigValue(const FLOAT value);
        ^
/usr/include/hyprlang.hpp:194:9: note: candidate constructor
        CConfigValue(const STRING value);
        ^
/usr/include/hyprlang.hpp:289:67: note: passing argument to parameter 'value' here
        void addConfigValue(const char* name, const CConfigValue& value);
                                                                  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
```

### How to reproduce

```
$ export CXXFLAGS=-m32
$ cmake -G Ninja -B /tmp/hyprland_build || meson setup /tmp/hyprland_build
$ cmake --build /tmp/hyprland_build || meson compile -C /tmp/hyprland_build
```

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/14452398/patch.txt)
I am guessing this is the fix as usual?

**Comment by jbeich** [comment]
Not yet but I don't see errors in other files:
```c++
../src/config/ConfigManager.cpp:373:57: error: call to constructor of 'const CConfigValue &' is ambiguous
    m_pConfig->addConfigValue("debug:watchdog_timeout", {5L});
                                                        ^~~~
```

**Comment by jbeich** [comment]
Confirming in advance: with `debug:watchdog_timeout` fixed both v0.36.0 and `main` branch build fine.

**Comment by vaxerski** [comment]
oops, right.
