### ISSUE TITLE
Wayland and Xwayland primary selection is not shared

### ISSUE THREAD

**Issue by hdm9527** [hyprwm/Hyprland#6603]
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch makepkg at commit fabc30df52ab5d2c369fc8acd4ff909a6ba3b8ac  (format: include macros for unreachable).
Date: Thu Jun 20 06:15:24 2024
Tag: v0.41.1-52-gfabc30df, commits: 4870

flags: (if any)
```

</details>

### Description

https://github.com/hyprwm/Hyprland/issues/6247#issuecomment-2176681444

### How to reproduce

above

**Comment by Moerliy** [comment]
Noticed it too.
I'm currently just running a detached script to keep them synced but would love to see this implemented.

**Comment by BasitAli** [comment]
> Noticed it too. I'm currently just running a detached script to keep them synced but would love to see this implemented.

Can you share the script?

**Comment by Moerliy** [comment]
> 
It's really bad and I already had some issues with it that I patched but the code is horrendous and pretty embarrassing tbh. You might want to look over it and change some things. 
I use it to sync text only and try to not f'up coping of other things under Wayland.
```bash
#!/usr/bin/env bash

# Kill any running instances of wl-paste
killall wl-paste 2>/dev/null

# Start wl-paste in watch mode to monitor clipboard changes on wayland
wl-paste -w 'xclip' 2>/dev/null &

lastclip=""

while true; do
  # Get the current x clipboard
  clip="$(xclip -o 2>/dev/null)"

  # clipboard changed and not "noText"
  if [[ "$clip" != "$lastclip" && "$clip" != "noText" ]]; then
    wlpaste="$(wl-paste)"
    # wl-paste contains other then text and clip content comes from wl-paste
    if [[ $(wl-paste -l | grep -c "text") -eq 0 && "$wlpaste" == "$clip" ]]; then
      echo "noText" | xclip
    else
      wl-copy "$clip"
    fi

    # Update the last clipboard content
    lastclip="$clip"
  fi

  # Sleep for a short interval before checking again
  sleep 0.1
done
```

**Comment by DrummyFloyd** [comment]
same issue , had to downgrade to 0.40

**Comment by vaxerski** [comment]
why do yall use middle click paste wth is wrong with yall

**Comment by zspher** [comment]
heres a shorter one line script for clipboard sync 
```
wl-paste -t text -w sh -c '[ "$(xclip -selection clipboard -o)" = "$(wl-paste -n)" ] || xclip -selection clipboard'
```

**Comment by Moltenkore** [comment]
> heres a shorter one line script for clipboard sync wl-paste -t text -w sh -c 'v=$(cat); cmp -s <(xclip -o -selection clipboard) <<< "$v" || xclip -selection clipboard <<< "$v"'
> 
> ```
> wl-paste -t text -w sh -c 'sleep 0.1 && [ "$(xclip -selection clipboard -o)" = "$(wl-paste -n)" ] && wl-copy "$(xclip -o)" || xclip -selection "clipboard primary"'
> ```
> 
> tested on brave & warframe

This doesn't work for me and I just get:
```
Error: target STRING not available
Nothing is copied
Error: target STRING not available
Nothing is copied
```

**Comment by hdm9527** [comment]
It's been a month, are there any plans to fix the clipboard sharing issue with wayland and xwayland?

**Comment by vaxerski** [comment]
primary? No. Clipboard? I haven't found a repro case, all seems to work on my end.

**Comment by hdm9527** [comment]
cliphist can't save the content copied from xwayland, use the following command to listen for the content copied by clipboard to be able to reproduce it.
```shell
wl-paste --type text --watch cliphist store
wl-paste --type image --watch cliphist store
```

**Comment by vaxerski** [comment]
@hdm9527 cliphist is a different issue reported wasnt it?

@BOTKooper will try, thanks

**Comment by vaxerski** [comment]
I installed bruno and can copy and paste text from it to kitty

**Comment by hdm9527** [comment]
My mistake. I misunderstood.

**Comment by BOTKooper** [comment]
> I installed bruno and can copy and paste text from it to kitty

I don't even know if it makes situation better (you prob running latest hypr?) or horribly worse (not reproducible on your machine / broken only in _some_ installations)

We'll see if 0.42 accidentally fixes it, if not - gonna try some shinanigans with my installation and report back

**Comment by vaxerski** [comment]
always test on -git

**Comment by BOTKooper** [comment]
> always test on -git

sadly I can't afford to bork my system so almost no -git packages for me (i blame python3.12 for giving me PTSD after doing `yay -Syu` couple of weeks ago on a monday morning)

**Comment by BasitAli** [comment]
It is a strange issue for sure, just tried to reproduce the steps that I atleast I notice:

1. Copied text from a chrome app (xwayland). VS Code on Xwayland behaves the same way.
2. Can paste into all chrome windows (xwayland) and other apps (wayland) such as kitty, sublime etc.
3. The only window I cannot paste into is Slack (Electron, wayland).
4. `cliphist` seems to have complete history. 

Will try another electron app to confirm. The script shared in this issue works to sync the clipboard.

**Comment by hdm9527** [comment]
This issue was opened for https://github.com/hyprwm/Hyprland/issues/6247#issuecomment-2176681444 https://github.com/hyprwm/Hyprland/issues/6247#issuecomment-2176932767. Need to change the title?

**Comment by BasitAli** [comment]
Just learned about Primary selection 🧠 . The title still holds true because I can see primary selection not being shared. Middle click is pasting different contents on the Wayland and Xwayland apps. I don't particularly care about this tbh, I just need my clipboards to be in sync.

**Comment by fiskhest** [comment]
> ```shell
> #!/bin/bash
> 
> while clipnotify; do
>   selection="$(xclip -o -selection clipboard 2>/dev/null)"
>   if [ $? -eq 0 ]; then
>     printf "%s" "$selection" | wl-copy
>   else
>     wl-paste | xclip -i
>   fi
> done
> ```

Couldn't get this working until I also turned off `wl-clip-persist`. Thanks!

**Comment by different-name** [comment]
Having this issue too, cannot paste into unity editor

**Comment by hdm9527** [comment]
When copying on the xwayland client, the log contains the error `[ERR] [xwm] Failed to read property notify cookie`.
```log
[LOG] [xwm] cb transfer to wl client complete, read 8 bytes
[ERR] [xwm] Failed to read property notify cookie
[LOG] [Window 55a8d98f13d0: title: "", class: ] destroyed, queueing.
[ERR] onWindowRemovedTiling node null?
[LOG] Unmapped [Window 55a8d98f13d0: title: ""] removed instantly
[LOG] [xwm] X clipboard at 55a8d9c1f410 takes clipboard
[LOG] [CWLDataDeviceProtocol] New selection for data source 55a8d9c1f410
[LOG] [CWLDataDeviceProtocol] CWLDataDeviceProtocol::setSelection: cannot send selection to a client without a data_device
[LOG] [CDataDeviceWLRProtocol] New selection for data source 55a8d9c1f410
[LOG] [CDataDeviceWLRProtocol] New  offer 55a8d9643370 for data source 55a8d9c1f410
[LOG] [CWLRDataOffer] Offer 55a8d9643370 asks to send data from source 55a8d9c1f410
[LOG] [XDataSource] send with mime text/plain;charset=utf-8 to fd 320
[LOG] [xwm] New XSurface at 55a8d91d3420 with xid of 2097196
[LOG] [xwm] New XWayland window at 55a8d98f13d0 for surf 55a8d91d3420
[LOG] [xwm] getTransferData
[LOG] [xwm] cb transfer to wl client complete, read 8 bytes
[ERR] [xwm] Failed to read property notify cookie
```

**Comment by Hi-Angel** [comment]
> why do yall use middle click paste wth is wrong with yall

*(I realize it's an old comment, but it comes from the project member, so it warrants an answer which no one gave yet)*

@vaxerski it's one of Linux features that I always show to people new to Linux. People are often investing into keyboard-focused workflow, but on Linux it is also possible to have mouse-focused workflow. It is when you need to copy text, but you don't even touch the keyboard, you just "double-click", "middle-paste", "double-click", "middle-paste".

Auditory for this starts with people like designers, project managers, and others, who have to work with mouse a lot. And then goes on to programmers, because not every programmers is equal, and some people for one or another reason can't or don't want to invest into improving their keyboard workflow with stuff like tiling WMs, etc.

But the biggest gains are for people who are able to combine both workflows 😊 So you usually stick to your keyboard, but once you have to take the mouse, you switch to the other workflow.

**P.S.**: another frequent usecase is to just copy-paste without "contaminating" the clipboard. The reasons vary from safety *(stuff like password or other sensitive information)* to just making sure you don't have to re-copy something that resides in the clipboard.

**Comment by Hi-Angel** [comment]
> but @fiskhest script works fine for now !

Hmm, unless I'm doing something wrong, as of 0.46 hyprland doesn't seem to work. How to reproduce:

1. Select a text in an app *(it seems it doesn't matter if you select in X11 or Wayland app)*
2. Start `emacs -Q`
3. Middle paste to it the selected text

Result: gets pasted anything but the text you actually selected.

**Comment by Hi-Angel** [comment]
@vaxerski I just edited the message to add yet another usecase. I hope this shows that primary clipboard is in fact a huge feature that simplifies lives of many people in so many different ways! 😊

*(I'll remove this message, posting just for the notification, because editing a msg doesn't notify)*

**Comment by Hi-Angel** [comment]
Summoning to the thread the v0.40.0 relase author, @vaxerski 

I just realized the issue is reported as a regression, but no one bisected yet to find the offending commit.

So I checked out `v0.40.0` and trying to build it, but I get compilation error:

```haskell
../subprojects/wlroots-hyprland/backend/drm/libliftoff.c: In function ‘commit’:
../subprojects/wlroots-hyprland/backend/drm/libliftoff.c:410:27: error: too few arguments to function ‘liftoff_output_apply’
  410 |                 int ret = liftoff_output_apply(crtc->liftoff, req, flags);
      |                           ^~~~~~~~~~~~~~~~~~~~
In file included from ../subprojects/wlroots-hyprland/backend/drm/libliftoff.c:2:
/usr/include/libliftoff.h:85:1: note: declared here
   85 | liftoff_output_apply(struct liftoff_output *output, drmModeAtomicReq *req,
      | ^~~~~~~~~~~~~~~~~~~~
[238/541] Compiling C++ object hyprctl/hyprctl.p/main.cpp.o
```

This looks like v0.40.0 is unbuildable, but then how did it work for project members?

**Comment by vaxerski** [comment]
downgrade libliftoff to 0.4.x

**Comment by Hi-Angel** [comment]
Thank you! It now fails with

```c++
../src/protocols/OutputManagement.cpp: In member function ‘void COutputHead::sendAllData()’:
../src/protocols/OutputManagement.cpp:169:64: error: cannot convert ‘wl_resource*’ to ‘CZwlrOutputModeV1*’
  169 |                 resource->sendCurrentMode(m->resource->resource());
      |                                           ~~~~~~~~~~~~~~~~~~~~~^~
      |                                                                |
      |                                                                wl_resource*
In file included from ../src/protocols/OutputManagement.hpp:7,
                 from ../src/protocols/OutputManagement.cpp:1:
protocols/wlr-output-management-unstable-v1.hpp:236:26: note:   initializing argument 1 of ‘void CZwlrOutputHeadV1::sendCurrentMode(CZwlrOutputModeV1*)’
  236 |     void sendCurrentMode(CZwlrOutputModeV1*);
      |                          ^~~~~~~~~~~~~~~~~~
../src/protocols/OutputManagement.cpp: In member function ‘void COutputHead::updateMode()’:
../src/protocols/OutputManagement.cpp:200:64: error: cannot convert ‘wl_resource*’ to ‘CZwlrOutputModeV1*’
  200 |                 resource->sendCurrentMode(m->resource->resource());
      |                                           ~~~~~~~~~~~~~~~~~~~~~^~
      |                                                                |
      |                                                                wl_resource*
protocols/wlr-output-management-unstable-v1.hpp:236:26: note:   initializing argument 1 of ‘void CZwlrOutputHeadV1::sendCurrentMode(CZwlrOutputModeV1*)’
  236 |     void sendCurrentMode(CZwlrOutputModeV1*);
      |                          ^~~~~~~~~~~~~~~~~~
[279/304] Compiling C++ object src/Hyprland.p/protocols_Screencopy.cpp.o
```

I dug into it a bit, but unfortunately the code uses `auto` all over the place, so it's impossible to figure out where and which types are used, and clangd navigation doesn't work either for some reason, presumably because the project wasn't fully built and so the `compile_commands.json` is incomplete.

**Comment by vaxerski** [comment]
downgrade hw-s

**Comment by Hi-Angel** [comment]
> downgrade hw-s

Thanks, sorry but can you clarify? I `git-grep`ped over the repo for word `hw-` and got nothing, so I'm not quite clear what dep are you referring to.

**Comment by vaxerski** [comment]
hyprwayland-scanner

**Comment by Hi-Angel** [comment]
> hyprwayland-scanner

Thanks. I downgraded it all the way down to 0.3.5, which is the lowest version Arch ever had and which matches 0.40 release month. The compilation error is still exactly the same.

**Comment by vaxerski** [comment]
you need to clear the generated files before recompiling. `rm ./protocols/*.hpp ./protocols/*.cpp`

**Comment by Hi-Angel** [comment]
> you need to clear the generated files before recompiling. `rm ./protocols/*.hpp ./protocols/*.cpp`

It started rebuilding everything, but in the end bailed out with the same compilation error.

**Comment by Hi-Angel** [comment]
Well, line numbers changed, but that's it

```
../src/protocols/OutputManagement.cpp: In member function ‘void COutputHead::sendAllData()’:
../src/protocols/OutputManagement.cpp:169:64: error: cannot convert ‘wl_resource*’ to ‘CZwlrOutputModeV1*’
  169 |                 resource->sendCurrentMode(m->resource->resource());
      |                                           ~~~~~~~~~~~~~~~~~~~~~^~
      |                                                                |
      |                                                                wl_resource*
In file included from ../src/protocols/OutputManagement.hpp:7,
                 from ../src/protocols/OutputManagement.cpp:1:
protocols/wlr-output-management-unstable-v1.hpp:213:26: note:   initializing argument 1 of ‘void CZwlrOutputHeadV1::sendCurrentMode(CZwlrOutputModeV1*)’
  213 |     void sendCurrentMode(CZwlrOutputModeV1*);
      |                          ^~~~~~~~~~~~~~~~~~
../src/protocols/OutputManagement.cpp: In member function ‘void COutputHead::updateMode()’:
../src/protocols/OutputManagement.cpp:200:64: error: cannot convert ‘wl_resource*’ to ‘CZwlrOutputModeV1*’
  200 |                 resource->sendCurrentMode(m->resource->resource());
      |                                           ~~~~~~~~~~~~~~~~~~~~~^~
      |                                                                |
      |                                                                wl_resource*
protocols/wlr-output-management-unstable-v1.hpp:213:26: note:   initializing argument 1 of ‘void CZwlrOutputHeadV1::sendCurrentMode(CZwlrOutputModeV1*)’
  213 |     void sendCurrentMode(CZwlrOutputModeV1*);
      |                          ^~~~~~~~~~~~~~~~~~
```

**Comment by cpiber** [comment]
> primary? No. Clipboard? I haven't found a repro case, all seems to work on my end.

I know that comment is a bit old, but there is one case where it doesn't work: Virtualbox. It probably does some shady stuff, but Wayland->Virtualbox with shared clipboard does not work to paste into the VM. Other way (copy in VM) works. Haven't noticed clipboard problems with other XWayland apps.

**Comment by cpiber** [comment]
@Hi-Angel According to my notes, building 0.40.0 required 0.3.4 specifically, 0.3.5 already introduced changes that broke the build

**Comment by Hi-Angel** [comment]
So, I managed to build 0.40.0 by using @cpiber's comment. I confirm the bug is a regression.

However, bisecting is very complicated because the project has commits that simply would not build. For example, commit a336b9b1 fails with error about `liftoff_output_apply` *(I just realize it's similar to one above)*. Apparently, somebody changed the API and forgotten to update deps in the commit that changed it. I tried git-blame'ing to `git checkout` a prior commit, but to no avail. That's sad…

**Comment by Hi-Angel** [comment]
CC: @vaxerski as the author of commit ea2501d4556f84d3de86a4ae2f4b22a474555b9f: buliding it fails with crazy amount of C++ errors, `rm ./protocols/*.hpp ./protocols/*.cpp` doesn't help

```
[1/195] Compiling C++ object hyprpm/src/hyprpm.p/progress_CProgressBar.cpp.o
FAILED: hyprpm/src/hyprpm.p/progress_CProgressBar.cpp.o 
ccache c++ -Ihyprpm/src/hyprpm.p -Ihyprpm/src -I../hyprpm/src -fdiagnostics-color=always -D_GLIBCXX_ASSERTIONS=1 -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -O3 -Wno-unused-parameter -Wno-unused-value -Wno-missing-field-initializers -Wno-narrowing -Wno-pointer-arith -DHAS_EXECINFO -DTOML_HEADER_ONLY=0 -DTOML_SHARED_LIB=1 -pthread -MD -MQ hyprpm/src/hyprpm.p/progress_CProgressBar.cpp.o -MF hyprpm/src/hyprpm.p/progress_CProgressBar.cpp.o.d -o hyprpm/src/hyprpm.p/progress_CProgressBar.cpp.o -c ../hyprpm/src/progress/CProgressBar.cpp
../hyprpm/src/progress/CProgressBar.cpp: In member function ‘void CProgressBar::print()’:
../hyprpm/src/progress/CProgressBar.cpp:72:32: error: ‘format’ is not a member of ‘std’
   72 |         message += "  " + std::format("{}%", static_cast<int>(percentDone * 100.0)) + " ";
      |                                ^~~~~~
../hyprpm/src/progress/CProgressBar.cpp:74:32: error: ‘format’ is not a member of ‘std’
   74 |         message += "  " + std::format("{} / {}", m_iSteps, m_iMaxSteps) + " ";
      |                                ^~~~~~
[3/195] Compiling C++ object hyprpm/src/hyprpm.p/main.cpp.o
FAILED: hyprpm/src/hyprpm.p/main.cpp.o 
ccache c++ -Ihyprpm/src/hyprpm.p -Ihyprpm/src -I../hyprpm/src -fdiagnostics-color=always -D_GLIBCXX_ASSERTIONS=1 -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -O3 -Wno-unused-parameter -Wno-unused-value -Wno-missing-field-initializers -Wno-narrowing -Wno-pointer-arith -DHAS_EXECINFO -DTOML_HEADER_ONLY=0 -DTOML_SHARED_LIB=1 -pthread -MD -MQ hyprpm/src/hyprpm.p/main.cpp.o -MF hyprpm/src/hyprpm.p/main.cpp.o.d -o hyprpm/src/hyprpm.p/main.cpp.o -c ../hyprpm/src/main.cpp
../hyprpm/src/main.cpp: In function ‘int main(int, char**, char**)’:
../hyprpm/src/main.cpp:47:21: error: ‘__gnu_cxx::__alloc_traits<std::allocator<std::__cxx11::basic_string<char> >, std::__cxx11::basic_string<char> >::value_type’ {aka ‘class std::__cxx11::basic_string<char>’} has no member named ‘starts_with’
   47 |         if (ARGS[i].starts_with("-")) {
      |                     ^~~~~~~~~~~
[4/195] Compiling C++ object protocols/libserver_protos.a.p/meson-generated_.._linux-dmabuf-v1.cpp.o
FAILED: protocols/libserver_protos.a.p/meson-generated_.._linux-dmabuf-v1.cpp.o 
ccache c++ -Iprotocols/libserver_protos.a.p -Iprotocols -I../protocols -fdiagnostics-color=always -D_GLIBCXX_ASSERTIONS=1 -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -O3 -Wno-unused-parameter -Wno-unused-value -Wno-missing-field-initializers -Wno-narrowing -Wno-pointer-arith -DHAS_EXECINFO -fPIC -MD -MQ protocols/libserver_protos.a.p/meson-generated_.._linux-dmabuf-v1.cpp.o -MF protocols/libserver_protos.a.p/meson-generated_.._linux-dmabuf-v1.cpp.o.d -o protocols/libserver_protos.a.p/meson-generated_.._linux-dmabuf-v1.cpp.o -c protocols/linux-dmabuf-v1.cpp
In file included from protocols/linux-dmabuf-v1.cpp:33:
protocols/linux-dmabuf-v1.hpp:211:22: error: ‘CWlBuffer’ has not been declared
  211 |     void sendCreated(CWlBuffer*);
      |                      ^~~~~~~~~
protocols/linux-dmabuf-v1.hpp:213:25: error: ‘CWlBuffer’ has not been declared
  213 |     void sendCreatedRaw(CWlBuffer*);
      |                         ^~~~~~~~~
protocols/linux-dmabuf-v1.cpp:223:6: error: variable or field ‘sendCreated’ declared void
  223 | void CZwpLinuxBufferParamsV1::sendCreated(CWlBuffer* buffer) {
      |      ^~~~~~~~~~~~~~~~~~~~~~~
protocols/linux-dmabuf-v1.cpp:223:43: error: ‘CWlBuffer’ was not declared in this scope; did you mean ‘wl_buffer’?
  223 | void CZwpLinuxBufferParamsV1::sendCreated(CWlBuffer* buffer) {
      |                                           ^~~~~~~~~
      |                                           wl_buffer
protocols/linux-dmabuf-v1.cpp:223:54: error: ‘buffer’ was not declared in this scope; did you mean ‘wl_buffer’?
  223 | void CZwpLinuxBufferParamsV1::sendCreated(CWlBuffer* buffer) {
      |                                                      ^~~~~~
      |                                                      wl_buffer
protocols/linux-dmabuf-v1.cpp:231:6: error: variable or field ‘sendCreatedRaw’ declared void
  231 | void CZwpLinuxBufferParamsV1::sendCreatedRaw(CWlBuffer* buffer) {
      |      ^~~~~~~~~~~~~~~~~~~~~~~
[…]
````

Bisecting this project is insanely hard, almost every commit fails to build in different ways… The last commit I found so far where the issue doesn't exist is fa69de8ab6cc17bb763a1586c55847c5d5a82a83.

**Comment by cpiber** [comment]
@Hi-Angel Did you test on latest git again? I noticed that shared clipboard with VirtualBox is working again (for 1-2 weeks?), so maybe your issue is solved now as well

**Comment by Hi-Angel** [comment]
@cpiber tested as of commit 708d1663, the issue is reproducible. By any chance, perhaps are you using the script referred to somewhere above? I tried it but it didn't work for me, but reading the comments it seems to work sporadically which is what you might be seeing.

**Comment by Hi-Angel** [comment]
@hdm9527 pls add `[BISECTED]` prefix to the title, so it's seen from the list of issues that the culprit is found. Might also be useful to copy the bisection result into the post or alternatively to put a link to the comment with the results *(or both)*.

**Comment by hdm9527** [comment]
@Hi-Angel This glitch has already been bisected. https://github.com/hyprwm/Hyprland/issues/6132#issuecomment-2128767072 https://github.com/hyprwm/Hyprland/issues/6247#issuecomment-2132199570

**Comment by Hi-Angel** [comment]
@hdm9527 well, the comment didn't explicitly say which commit is bad, it just referred to "some good commit". But more importantly, you didn't mention it in the bugreport description.

It's nice you mentioned it a month later after the bisection effort started and multiple people including a project maintainer took their time to work on that.

Now please, do add this information to the bugreport.

**Comment by Hi-Angel** [comment]
Trying Hyprland again, see there's no activity on the bug.

@vaxerski the regressing commit doesn't seem to say it fixed anything, lacks motivation and triples the number of LOC. Given this, and that we also found it to introduce regression, I suggest we revert it. If that's okay with you, I can send a PR on the weekend.

**Comment by Hi-Angel** [comment]
Been too many changes relying on it?

**Comment by vaxerski** [comment]
yes

**Comment by vaxerski** [comment]
Hello there!

This issue has been closed, as we are moving from issues to discussions. More about this can be found [here](https://wiki.hyprland.org/Contributing-and-Debugging/Issue-Guidelines/) and in #9854.

Firstly, please make sure this issue is still relevant in latest Hyprland. If so, we ask you to open a [discussion](https://github.com/hyprwm/Hyprland/discussions) (please read the discussion guidelines first, in the pinned post)

Thank you for your understanding!

**Comment by Hi-Angel** [comment]
Wow. Maybe someone's who's still using Hyprland is motivated to do the work, but this attitude of: 1. introduce significant regression 2. don't care to even fix it 3. close the issue having hours of contributor's work for bisection instead of bothering to transfer it — it's just, let's say, not very good.

**Comment by vaxerski** [comment]
I closed all issues equally. If anyone is interested in the issue, they can make a discussion where they link this issue. It's not like the comments are deleted.

**Comment by Hi-Angel** [comment]
Good news, it's almost fixed! Wayland → X11 now works.

X11 → Wayland doesn't work yet though.

**P.S.**: @hyperair @kRHYME7 curious to hear why the downvotes, was something wrong with my comment?
