### PR TITLE
Unbreak Meson build on FreeBSD

### PR DESCRIPTION
**Pull request by jbeich**
Regressed by #3543

```c++
$ meson setup /tmp/hyprland_build
$ meson compile -C /tmp/hyprland_build
[...]
In file included from src/pch/pch.hpp:1:
In file included from src/Compositor.hpp:7:
In file included from src/defines.hpp:1:
In file included from src/includes.hpp:148:
In file included from src/helpers/Vector2D.hpp:5:
src/helpers/../macros.hpp:17:10: fatal error: 'version.h' file not found
   17 | #include "version.h"
      |          ^~~~~~~~~~~
```

### CODE REVIEW

File: scripts/generateVersion.sh [hunk 1]
```diff
@@ -1,14 +1,14 @@
...
 
-awk -i inplace "{sub(/@HASH@/,\"${HASH}\")}1" ./src/version.h
-awk -i inplace "{sub(/@BRANCH@/,\"${BRANCH}\")}1" ./src/version.h
-awk -i inplace "{sub(/@MESSAGE@/,\"${MESSAGE}\")}1" ./src/version.h
-awk -i inplace "{sub(/@DIRTY@/,\"${DIRTY}\")}1" ./src/version.h
-awk -i inplace "{sub(/@TAG@/,\"${TAG}\")}1" ./src/version.h
\ No newline at end of file
+sed -i -e "s/@HASH@/${HASH}/" ./src/version.h
+sed -i -e "s/@BRANCH@/${BRANCH}/" ./src/version.h
+sed -i -e "s/@MESSAGE@/${MESSAGE}/" ./src/version.h
```
Comment (vaxerski) [inline scripts/generateVersion.sh:12]: message can contain weird characters like `/` which will destroy this command. We only sanitize `#` and `"`

**Comment by vaxerski** [comment]
and it wouldn't work here? why?

**Comment by jbeich** [comment]
`-i inplace` isn't supported as documented in e1e9c98 commit message. Besides, I don't think `awk` is any better here given it consumers double-quotes in `"dirty"`.

File: scripts/generateVersion.sh (hunk 1 above)
Comment (jbeich) [reply scripts/generateVersion.sh]: Fixed by using one of the sanitized characters as a the delimited for `s` sed command.

Also, why `#` is sanitized? It doesn't start a comment in C/C++ and has no impact within quotes in Bourne-style shells.

Comment (jbeich) [reply scripts/generateVersion.sh]: Applied `\"` consistently to avoid surprises from tags or (local) branches containing `/` slash.

Comment (jbeich) [reply scripts/generateVersion.sh]: > why `#` is sanitized?

Ah, it's for GNU awk. For best compat with the previous behavior I'll switch to `#` as delimiter.
