### ISSUE TITLE
Waydroid Full Screen Issue

### ISSUE THREAD

**Issue by tomjpalamattam** [hyprwm/Hyprland#5236]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch HEAD at commit c5e28ebcfe00a510922779b2c568cfa52a317445  (props: bump ver 0.37.1).
Date: Sat Mar 16 14:51:49 2024
Tag: v0.37.1

flags: (if any)


System Information:
System name: Linux
Node name: archlinux
Release: 6.8.1-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Sat, 16 Mar 2024 17:15:23 +0000


GPU information:
00:02.0 VGA compatible controller [0300]: Intel Corporation CoffeeLake-H GT2 [UHD Graphics 630] [8086:3e9b] (prog-if 00 [VGA controller])
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU117M [GeForce GTX 1650 Mobile / Max-Q] [10de:1f99] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

I have recently updated hyprland to the latest version from arch repos 0.37.1-1 from 0.36.0-1. I am now facing graphical glitches (see attached video) while trying to maximize waydroid using :

````bash
waydroid show-full-ui
````
**the keybind i used was:**
````
bind = SUPER, F, fullscreen,
````

This did not happen in previous version

Here are link to my configs:
https://github.com/tomjpalamattam/dotfiles/blob/main/.config/hypr/hyprland.conf
https://github.com/tomjpalamattam/dotfiles/blob/main/.config/hypr/keybinds.conf
https://github.com/tomjpalamattam/dotfiles/blob/main/.config/hypr/env.conf

### How to reproduce

in terminal:
````bash
waydroid show-full-ui
````

use the keybinding:

````
bind = SUPER, F, fullscreen,
````

### Crash reports, logs, images, videos

[hyprland.log](https://github.com/hyprwm/Hyprland/files/14733473/hyprland.log)

https://github.com/hyprwm/Hyprland/assets/32675052/ab136402-f7d7-480b-a128-0f62ecf9eb7d

**Comment by tomjpalamattam** [comment]
This was the behavior in version `0.36.0-1. I`

https://github.com/hyprwm/Hyprland/assets/32675052/22fde5a7-0179-4738-8c7a-184210ba8542

**Comment by vaxerski** [comment]
can you git bisect this?

**Comment by tomjpalamattam** [comment]
I tried it, but I could not compile it because of dependency issues

`[43/114] Building CXX object CMakeFiles/Hyprland.dir/src/events/Devices.cpp.o
FAILED: CMakeFiles/Hyprland.dir/src/events/Devices.cpp.o
/usr/bin/c++ -DHAS_EXECINFO -DHyprland_EXPORTS -DUSES_SYSTEMD -DWLR_USE_UNSTABLE -I/home/tom/Hyprland/. -I/home/tom/Hyprland/src -I/home/tom/Hyprland/subprojects/wlroots/include -I/home/tom/Hyprland/subprojects/wlroots/build/include -I/home/tom/Hyprland/subprojects/udis86 -I/home/tom/Hyprland/protocols -I/home/tom/Hyprland/subprojects/udis86/libudis86 -isystem /usr/include/libdrm -isystem /usr/include/pango-1.0 -isystem /usr/include/cairo -isystem /usr/include/glib-2.0 -isystem /usr/lib/glib-2.0/include -isystem /usr/include/harfbuzz -isystem /usr/include/freetype2 -isystem /usr/include/pixman-1 -isystem /usr/include/libpng16 -isystem /usr/include/libmount -isystem /usr/include/blkid -isystem /usr/include/sysprof-6 -isystem /usr/include/fribidi -O3 -DNDEBUG -std=gnu++23 -O3 -Wall -Wextra -Wno-unused-parameter -Wno-unused-value -Wno-missing-field-initializers -Wno-narrowing -Wno-pointer-arith -pthread -Winvalid-pch -include /home/tom/Hyprland/build/CMakeFiles/Hyprland.dir/cmake_pch.hxx -MD -MT CMakeFiles/Hyprland.dir/src/events/Devices.cpp.o -MF CMakeFiles/Hyprland.dir/src/events/Devices.cpp.o.d -o CMakeFiles/Hyprland.dir/src/events/Devices.cpp.o -c /home/tom/Hyprland/src/events/Devices.cpp
/home/tom/Hyprland/src/events/Devices.cpp: In function ‘void Events::listener_newInput(wl_listener*, void*)’:
/home/tom/Hyprland/src/events/Devices.cpp:77:14: error: ‘WLR_INPUT_DEVICE_TABLET_TOOL’ was not declared in this scope; did you mean ‘WLR_INPUT_DEVICE_TABLET_PAD’?
   77 |         case WLR_INPUT_DEVICE_TABLET_TOOL:
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |              WLR_INPUT_DEVICE_TABLET_PAD
[50/114] Building CXX object CMakeFiles/Hyprland.dir/src/config/ConfigManager.cpp.o
ninja: build stopped: subcommand failed.
make[1]: *** [Makefile:15: release] Error 1
make[1]: Leaving directory '/home/tom/Hyprland'
make: *** [Makefile:31: all] Error 2`

I tried downgrading these packages, but it was of no use

`gdb ninja gcc cmake meson libxcb xcb-proto xcb-util xcb-util-keysyms libxfixes libx11 libxcomposite xorg-xinput libxrender pixman wayland-protocols cairo pango seatd libxkbcommon xcb-util-wm xorg-xwayland libinput libliftoff libdisplay-info cpio tomlplusplus hyprlang hyprcursor`

If you can suggest which package should i downgrade, I can try again

**Comment by vaxerski** [comment]
no downgrading, you just forgot to run `g reset --hard --recurse-submodules` after bisect throws you onto a new commit.

**Comment by tomjpalamattam** [comment]
You were right, sorry for the confusion.

````
f4f3aa2e505ca1b22688fb4a32f31c4bfb851dd0 is the first bad commit
commit f4f3aa2e505ca1b22688fb4a32f31c4bfb851dd0
Author: vaxerski <vaxry@vaxry.net>
Date:   Wed Feb 28 11:45:43 2024 +0000

    layout: add size prediction for initial xdg commits

    fixes #4022

 src/events/Windows.cpp       |  4 ++-
 src/layout/DwindleLayout.cpp | 66 ++++++++++++++++++++++++++++++++++++++------
 src/layout/DwindleLayout.hpp |  1 +
 src/layout/IHyprLayout.cpp   |  4 +++
 src/layout/IHyprLayout.hpp   |  6 ++++
 src/layout/MasterLayout.cpp  | 27 ++++++++++++++++++
 src/layout/MasterLayout.hpp  |  1 +
 7 files changed, 100 insertions(+), 9 deletions(-)
````

**Comment by vaxerski** [comment]
looks like a waydroid issue then. Try adding a `float` windowrule to it.

**Comment by tomjpalamattam** [comment]
> looks like a waydroid issue then. Try adding a `float` windowrule to it.

That actually helped. And for anyone who would like to have old behavior back, you can use the following commands

````
sudo waydroid shell
# setprop persist.waydroid.multi_windows false
# setprop persist.waydroid.width 1920
# setprop persist.waydroid.height 1080
# exit
````

**Comment by tomjpalamattam** [comment]
I am closing this issue

**Comment by vaxerski** [comment]
yeah that's a waydroid issue, seems like it doesn't cope well with being requested a size at launch.
