### ISSUE TITLE
throws an error "you have incompatible xdg portals implementations installed" when building on ubuntu 23.04

### ISSUE THREAD

**Issue by Vertecedoc4545** [hyprwm/Hyprland#2195]
after building on ubuntu 23.04 and running, it gives the error you have incompatible xdg portals implementations installed in the screen,

the install instructions i followed are the same im pull requesting (https://github.com/Vertecedoc4545/hyprland-wiki-ubuntu/blob/main/pages/Getting%20Started/Ubuntu.md) , im unaware about its reproducibility as i didnt notice this error days ago with the same build instructions

**Comment by bvr-yr** [comment]
its cause of `xdg-desktop-portal-gnome`

btw even masking it through systemctl throws error anyway
maybe it's a point to turn off notification if wrong impls are installed but not started?

**Comment by tchofy** [comment]
Hyprland just checks if they're installed, not specifically if they're running, although I agree that the message makes more sense if other portals are running alongside either xdgdp-wlr or xdgdp-hyprland, but apparently just having it installed is enough for issues to happen.

Just throw `suppress_portal_warnings = true` inside the misc{} part of your config, if you have issues try uninstalling the gnome portal.

**Comment by vaxerski** [comment]
it's not an error per se, it's a warning. Expected behavior

**Comment by Vertecedoc4545** [comment]
perfect

**Comment by Vertecedoc4545** [comment]
a good idea would be to change the ui color to orange and instead of the word remove lets put add "this" to the config if no more errors ocur, or lets change the behavior to look for running portals.
that may improve accesibility

**Comment by DreamMaoMao** [comment]
> Hyprland just checks if they're installed, not specifically if they're running, although I agree that the message makes more sense if other portals are running alongside either xdgdp-wlr or xdgdp-hyprland, but apparently just having it installed is enough for issues to happen.
> 
> Just throw `suppress_portal_warnings = true` inside the misc{} part of your config, if you have issues try uninstalling the gnome portal.

hi! I added "suppress_portal_warnings = true" in the misc block, but it threw an **exception**:
**"<suppress_portal_warnings> :no such field"**

**Comment by tchofy** [comment]
> > Hyprland just checks if they're installed, not specifically if they're running, although I agree that the message makes more sense if other portals are running alongside either xdgdp-wlr or xdgdp-hyprland, but apparently just having it installed is enough for issues to happen.
> > Just throw `suppress_portal_warnings = true` inside the misc{} part of your config, if you have issues try uninstalling the gnome portal.
> 
> hi! I added "suppress_portal_warnings = true" in the misc block, but it threw an **exception**: **"<suppress_portal_warnings> :no such field"**

Is your hyprland build up to date? That option was introduced in https://github.com/hyprwm/Hyprland/commit/a8b3be2c9c916870b826cba8fdf3aec1046d2f81, if you try it on an older version it'll give you that error.

**Comment by DreamMaoMao** [comment]
> > > Hyprland just checks if they're installed, not specifically if they're running, although I agree that the message makes more sense if other portals are running alongside either xdgdp-wlr or xdgdp-hyprland, but apparently just having it installed is enough for issues to happen.
> > > Just throw `suppress_portal_warnings = true` inside the misc{} part of your config, if you have issues try uninstalling the gnome portal.
> > 
> > 
> > hi! I added "suppress_portal_warnings = true" in the misc block, but it threw an **exception**: **"<suppress_portal_warnings> :no such field"**
> 
> Is your hyprland build up to date? That option was introduced in [a8b3be2](https://github.com/hyprwm/Hyprland/commit/a8b3be2c9c916870b826cba8fdf3aec1046d2f81), if you try it on an older version it'll give you that error.

I use the source version is v0.24.0, I will try to use the latest source,thanks !

**Comment by DreamMaoMao** [comment]
> tchofy

![image](https://github.com/hyprwm/Hyprland/assets/30348075/a81f6d40-9512-4c88-a4d5-05fb6e0beb70)
![image](https://github.com/hyprwm/Hyprland/assets/30348075/521d3b8c-c088-44e5-99c7-19a964bb21c8)
v24.0 i s support  **suppress_portal_warnings**,but i still can not use it.

**Comment by DreamMaoMao** [comment]
> > > Hyprland just checks if they're installed, not specifically if they're running, although I agree that the message makes more sense if other portals are running alongside either xdgdp-wlr or xdgdp-hyprland, but apparently just having it installed is enough for issues to happen.
> > > Just throw `suppress_portal_warnings = true` inside the misc{} part of your config, if you have issues try uninstalling the gnome portal.
> > 
> > 
> > hi! I added "suppress_portal_warnings = true" in the misc block, but it threw an **exception**: **"<suppress_portal_warnings> :no such field"**
> 
> Is your hyprland build up to date? That option was introduced in [a8b3be2](https://github.com/hyprwm/Hyprland/commit/a8b3be2c9c916870b826cba8fdf3aec1046d2f81), if you try it on an older version it'll give you that error.

I change the value in source and rebuild it,it work now
