### ISSUE TITLE
Fails to build with Clang

### ISSUE THREAD

**Issue by jbeich** [hyprwm/Hyprland#5765]
### Hyprland Version

v0.39.1-86-g25aec3ac

### Bug or Regression?

Bug

### Description

Regressed by 25aec3ac8ce6: trailing emoji in identifier.

### How to reproduce

```c++
$ export CXX=clang++
$ cmake -B _build
$ cmake --build _build
[...]
src/protocols/PointerConstraints.cpp:211:88: error: character <U+1F95A> not allowed in an identifier
  211 | void CPointerConstraintsProtocol::destroyPointerConstraint(CPointerConstraint* hyprland🥚) {
      |                                                                                        ^~
src/protocols/PointerConstraints.cpp:212:90: error: character <U+1F95A> not allowed in an identifier
  212 |     std::erase_if(m_vConstraints, [&](const auto& other) { return other.get() == hyprland🥚; });
      |                                                                                          ^~
```

**Comment by vaxerski** [comment]
why does clang not allow easter eggs? :(
