### ISSUE TITLE
NO_XWAYLAND build is broken since db24964

### ISSUE THREAD

**Issue by Piroro-hs** [hyprwm/Hyprland#8759]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

Not relevant

### Description

`NO_XWAYLAND` build is broken since db24964, as `Dnd.cpp` includes `XWM.hpp` unconditionally.

### How to reproduce

```sh
cmake --no-warn-unused-cli -B build -G Ninja -D CMAKE_BUILD_TYPE=Release -D NO_XWAYLAND=true
cmake --build build
```

### Crash reports, logs, images, videos

[cmake_build_log.txt](https://github.com/user-attachments/files/18181104/cmake_build_log.txt)

**Comment by vaxerski** [comment]
check now

**Comment by Piroro-hs** [comment]
```
/src/xwayland/Dnd.cpp:10:8: error: ‘xcb_atom_t’ does not name a type
   10 | static xcb_atom_t dndActionToAtom(uint32_t actions) {
      |        ^~~~~~~~~~
```

**Comment by vaxerski** [comment]
that's already fixed in git no? https://github.com/hyprwm/Hyprland/commit/0fec38fe727954e5c4cf51423a6aba03646ad5da

**Comment by Piroro-hs** [comment]
Oops, I only pulled 4c4471c. Fixed. Thanks!
